server:
  port: ${APP_PORT} 

spring:
  application:
    name: "bank-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    initialization-mode: always

app:
  sms:
    enable: true
  email:
    from: "no-reply@alinebank.com"
    enable: true
  security:
    secret-key: "${ENCRYPT_SECRET_KEY}"
    jwt:
      secret-key: "${JWT_SECRET_KEY}"
  aws:
    email:
      template-bucket-name: "aline-bank-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"
