apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "aline-secret-d998b45e"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
          - path: dbname
            objectAlias: dbname
          - path: host
            objectAlias: dbhost
          - path: jwt_key
            objectAlias: jwtkey
          - path: encrypt_key
            objectAlias: encryptkey
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: aline-secret
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias> 
        - key: db-user
          objectName: dbusername
        - key: db-pass
          objectName: dbpassword
        - key: db-name
          objectName: dbname
        - key: db-host
          objectName: dbhost
        - key: jwt-key
          objectName: jwtkey
        - key: encrypt-key
          objectName: encryptkey
          
        
